-- =============================================================================
-- Schema: shipping
-- Sistema de cotação e logística de frete
-- =============================================================================

create schema if not exists shipping;

-- Reutiliza a função set_updated_at do schema integrations
-- (já criada em 20260209195000_create_integrations_and_yampi_tables.sql)

-- =============================================================================
-- shipping.product_dimensions — Catálogo de dimensões dos produtos
-- =============================================================================

create table if not exists shipping.product_dimensions (
  id bigint generated by default as identity primary key,
  store_id uuid references integrations.stores(id) on delete set null,
  sku text not null,
  product_name text not null,
  weight_grams integer not null default 0 check (weight_grams >= 0),
  height_cm numeric(8,2) not null default 0 check (height_cm >= 0),
  width_cm numeric(8,2) not null default 0 check (width_cm >= 0),
  length_cm numeric(8,2) not null default 0 check (length_cm >= 0),
  source_platform text check (source_platform in ('yampi', 'cartpanda', 'abacatepay', 'appmax')),
  source_product_id text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, sku)
);

create index if not exists idx_shipping_product_dimensions_sku
  on shipping.product_dimensions (sku);
create index if not exists idx_shipping_product_dimensions_store
  on shipping.product_dimensions (store_id);
create index if not exists idx_shipping_product_dimensions_source
  on shipping.product_dimensions (source_platform, source_product_id);

drop trigger if exists trg_shipping_product_dimensions_updated_at on shipping.product_dimensions;
create trigger trg_shipping_product_dimensions_updated_at
before update on shipping.product_dimensions
for each row execute function integrations.set_updated_at();

-- =============================================================================
-- shipping.unified_orders — Pedidos unificados de todas as plataformas
-- =============================================================================

create table if not exists shipping.unified_orders (
  id bigint generated by default as identity primary key,
  order_uuid uuid not null unique default gen_random_uuid(),
  store_id uuid references integrations.stores(id) on delete set null,

  -- Origem do pedido
  source_platform text not null
    check (source_platform in ('yampi', 'cartpanda', 'abacatepay', 'appmax')),
  source_order_id text not null,
  source_order_number text,
  source_event_id bigint references integrations.integration_events(id) on delete set null,

  -- Cliente
  customer_name text,
  customer_email text,
  customer_phone text,
  customer_cpf text,

  -- Endereço de envio
  shipping_name text,
  shipping_address text,
  shipping_number text,
  shipping_complement text,
  shipping_neighborhood text,
  shipping_city text,
  shipping_state text,
  shipping_zip text,
  shipping_country text not null default 'BR',

  -- Itens (jsonb array)
  items jsonb not null default '[]'::jsonb,

  -- Dimensões do pacote (calculadas)
  package_weight_grams integer not null default 0 check (package_weight_grams >= 0),
  package_height_cm numeric(8,2) not null default 0 check (package_height_cm >= 0),
  package_width_cm numeric(8,2) not null default 0 check (package_width_cm >= 0),
  package_length_cm numeric(8,2) not null default 0 check (package_length_cm >= 0),

  -- Valores
  total_cents integer not null default 0,
  shipping_cents integer not null default 0,

  -- Status do pedido
  status text not null default 'pending'
    check (status in (
      'pending',           -- Recebido, aguardando cotação
      'quoted',            -- Cotação realizada
      'approved',          -- Cotação aprovada, aguardando compra de etiqueta
      'label_purchased',   -- Etiqueta comprada
      'separating',        -- Em separação
      'shipped',           -- Enviado
      'in_transit',        -- Em trânsito
      'delivered',         -- Entregue
      'cancelled',         -- Cancelado
      'returned'           -- Devolvido
    )),

  -- Timestamps de cada etapa
  quoted_at timestamptz,
  approved_at timestamptz,
  label_at timestamptz,
  separated_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz,

  -- Observações
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Evita duplicidade: um pedido de uma plataforma só pode ser unificado uma vez
  unique (source_platform, source_order_id)
);

create index if not exists idx_shipping_unified_orders_status
  on shipping.unified_orders (status);
create index if not exists idx_shipping_unified_orders_platform
  on shipping.unified_orders (source_platform);
create index if not exists idx_shipping_unified_orders_store
  on shipping.unified_orders (store_id);
create index if not exists idx_shipping_unified_orders_created
  on shipping.unified_orders (created_at desc);
create index if not exists idx_shipping_unified_orders_customer_email
  on shipping.unified_orders (lower(customer_email));
create index if not exists idx_shipping_unified_orders_zip
  on shipping.unified_orders (shipping_zip);

drop trigger if exists trg_shipping_unified_orders_updated_at on shipping.unified_orders;
create trigger trg_shipping_unified_orders_updated_at
before update on shipping.unified_orders
for each row execute function integrations.set_updated_at();

-- =============================================================================
-- shipping.quotes — Cotações de frete
-- =============================================================================

create table if not exists shipping.quotes (
  id bigint generated by default as identity primary key,
  order_id bigint not null references shipping.unified_orders(id) on delete cascade,

  -- Provedor e transportadora
  carrier_provider text not null
    check (carrier_provider in ('correios', 'melhor_envio', 'kangu', 'frenet', 'manual')),
  carrier_name text not null,
  carrier_service_code text,
  external_service_id text,

  -- Valores
  price_cents integer not null default 0 check (price_cents >= 0),
  discount_cents integer not null default 0 check (discount_cents >= 0),
  final_price_cents integer not null default 0 check (final_price_cents >= 0),

  -- Prazo de entrega
  delivery_min_days integer,
  delivery_max_days integer,

  -- Seleção
  selected boolean not null default false,
  auto_selected boolean not null default false,

  -- Validade
  expires_at timestamptz,

  -- Resposta crua da API
  raw_response jsonb,

  created_at timestamptz not null default now()
);

create index if not exists idx_shipping_quotes_order
  on shipping.quotes (order_id);
create index if not exists idx_shipping_quotes_selected
  on shipping.quotes (order_id) where selected = true;

-- =============================================================================
-- shipping.labels — Etiquetas de envio
-- =============================================================================

create table if not exists shipping.labels (
  id bigint generated by default as identity primary key,
  order_id bigint not null references shipping.unified_orders(id) on delete cascade,
  quote_id bigint references shipping.quotes(id) on delete set null,

  -- Provedor e IDs externos
  carrier_provider text not null
    check (carrier_provider in ('correios', 'melhor_envio', 'kangu', 'frenet', 'manual')),
  external_label_id text,
  external_order_id text,

  -- Transportadora
  carrier_name text,
  service_name text,

  -- Rastreio
  tracking_code text,
  tracking_url text,

  -- Etiqueta (PDF)
  label_url text,

  -- Valor
  price_cents integer not null default 0 check (price_cents >= 0),

  -- Status
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'ready', 'printed', 'cancelled')),

  -- Timestamps
  purchased_at timestamptz,
  printed_at timestamptz,
  cancelled_at timestamptz,

  -- Resposta crua
  raw_response jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_shipping_labels_order
  on shipping.labels (order_id);
create index if not exists idx_shipping_labels_tracking
  on shipping.labels (tracking_code);
create index if not exists idx_shipping_labels_status
  on shipping.labels (status);

drop trigger if exists trg_shipping_labels_updated_at on shipping.labels;
create trigger trg_shipping_labels_updated_at
before update on shipping.labels
for each row execute function integrations.set_updated_at();

-- =============================================================================
-- shipping.tracking_events — Eventos de rastreio
-- =============================================================================

create table if not exists shipping.tracking_events (
  id bigint generated by default as identity primary key,
  label_id bigint not null references shipping.labels(id) on delete cascade,
  order_id bigint not null references shipping.unified_orders(id) on delete cascade,
  tracking_code text not null,

  event_type text,
  event_description text,
  event_location text,
  event_date timestamptz,

  raw jsonb,

  created_at timestamptz not null default now()
);

create index if not exists idx_shipping_tracking_events_label
  on shipping.tracking_events (label_id);
create index if not exists idx_shipping_tracking_events_order
  on shipping.tracking_events (order_id);
create index if not exists idx_shipping_tracking_events_code
  on shipping.tracking_events (tracking_code);

-- =============================================================================
-- shipping.notification_log — Log de notificações enviadas ao cliente
-- =============================================================================

create table if not exists shipping.notification_log (
  id bigint generated by default as identity primary key,
  order_id bigint not null references shipping.unified_orders(id) on delete cascade,

  channel text not null check (channel in ('whatsapp', 'email', 'sms')),
  recipient text not null,
  template_name text,
  message_text text,

  status text not null default 'sent'
    check (status in ('sent', 'failed', 'delivered', 'read')),

  sent_at timestamptz not null default now(),
  delivered_at timestamptz,
  read_at timestamptz,
  error_text text,

  raw_response jsonb
);

create index if not exists idx_shipping_notification_log_order
  on shipping.notification_log (order_id);
create index if not exists idx_shipping_notification_log_status
  on shipping.notification_log (status);

-- =============================================================================
-- shipping.settings — Configurações do sistema
-- =============================================================================

create table if not exists shipping.settings (
  id bigint generated by default as identity primary key,
  store_id uuid references integrations.stores(id) on delete cascade,
  key text not null,
  value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, key)
);

drop trigger if exists trg_shipping_settings_updated_at on shipping.settings;
create trigger trg_shipping_settings_updated_at
before update on shipping.settings
for each row execute function integrations.set_updated_at();

-- =============================================================================
-- Grants — service_role e authenticated
-- =============================================================================

grant usage on schema shipping to service_role;
grant all on all tables in schema shipping to service_role;
grant all on all sequences in schema shipping to service_role;

grant usage on schema shipping to authenticated;
grant select on shipping.unified_orders to authenticated;
grant select on shipping.quotes to authenticated;
grant select on shipping.labels to authenticated;
grant select on shipping.tracking_events to authenticated;
grant select on shipping.notification_log to authenticated;
grant select, insert, update, delete on shipping.product_dimensions to authenticated;
grant select, insert, update on shipping.settings to authenticated;
grant usage on all sequences in schema shipping to authenticated;

-- =============================================================================
-- RLS — Row Level Security
-- =============================================================================

alter table shipping.unified_orders enable row level security;
alter table shipping.quotes enable row level security;
alter table shipping.labels enable row level security;
alter table shipping.tracking_events enable row level security;
alter table shipping.notification_log enable row level security;
alter table shipping.product_dimensions enable row level security;
alter table shipping.settings enable row level security;

-- Policy: membros da loja podem ver pedidos da sua loja
create policy "Store members can view their orders"
  on shipping.unified_orders for select to authenticated
  using (
    store_id in (
      select sm.store_id from integrations.store_members sm
      where sm.user_id = auth.uid()
    )
    or store_id is null  -- pedidos sem loja associada são visíveis para todos autenticados
  );

create policy "Store members can view their quotes"
  on shipping.quotes for select to authenticated
  using (
    order_id in (
      select uo.id from shipping.unified_orders uo
      where uo.store_id in (
        select sm.store_id from integrations.store_members sm
        where sm.user_id = auth.uid()
      )
      or uo.store_id is null
    )
  );

create policy "Store members can view their labels"
  on shipping.labels for select to authenticated
  using (
    order_id in (
      select uo.id from shipping.unified_orders uo
      where uo.store_id in (
        select sm.store_id from integrations.store_members sm
        where sm.user_id = auth.uid()
      )
      or uo.store_id is null
    )
  );

create policy "Store members can view their tracking"
  on shipping.tracking_events for select to authenticated
  using (
    order_id in (
      select uo.id from shipping.unified_orders uo
      where uo.store_id in (
        select sm.store_id from integrations.store_members sm
        where sm.user_id = auth.uid()
      )
      or uo.store_id is null
    )
  );

create policy "Store members can view their notifications"
  on shipping.notification_log for select to authenticated
  using (
    order_id in (
      select uo.id from shipping.unified_orders uo
      where uo.store_id in (
        select sm.store_id from integrations.store_members sm
        where sm.user_id = auth.uid()
      )
      or uo.store_id is null
    )
  );

create policy "Store members can manage product dimensions"
  on shipping.product_dimensions for all to authenticated
  using (
    store_id in (
      select sm.store_id from integrations.store_members sm
      where sm.user_id = auth.uid()
    )
    or store_id is null
  )
  with check (
    store_id in (
      select sm.store_id from integrations.store_members sm
      where sm.user_id = auth.uid()
      and sm.role in ('owner', 'admin', 'member')
    )
    or store_id is null
  );

create policy "Store members can manage settings"
  on shipping.settings for all to authenticated
  using (
    store_id in (
      select sm.store_id from integrations.store_members sm
      where sm.user_id = auth.uid()
    )
    or store_id is null
  )
  with check (
    store_id in (
      select sm.store_id from integrations.store_members sm
      where sm.user_id = auth.uid()
      and sm.role in ('owner', 'admin')
    )
    or store_id is null
  );

-- =============================================================================
-- Realtime — habilitar para o dashboard receber atualizações em tempo real
-- =============================================================================

alter publication supabase_realtime add table shipping.unified_orders;
alter publication supabase_realtime add table shipping.labels;
alter publication supabase_realtime add table shipping.tracking_events;

-- =============================================================================
-- View: pedidos pagos ainda não unificados (usada pela Edge Function shipping-order-unifier)
-- =============================================================================

create or replace view shipping.pending_yampi_orders as
select
  yo.id as yampi_row_id,
  yo.merchant_id,
  yo.yampi_order_id,
  yo.order_number,
  yo.integration_event_id,
  yo.payment_status,
  yo.total_cents,
  yo.shipping_cents,
  yo.source_created_at,
  yc.name as customer_name,
  yc.email as customer_email,
  yc.phone_full_number as customer_phone,
  yc.cpf as customer_cpf,
  ya.receiver as shipping_name,
  ya.street as shipping_address,
  ya.street_number as shipping_number,
  ya.complement as shipping_complement,
  ya.neighborhood as shipping_neighborhood,
  ya.city as shipping_city,
  ya.state as shipping_state,
  ya.zipcode as shipping_zip,
  ya.country as shipping_country
from yampi.orders yo
left join yampi.customers yc on yc.id = yo.yampi_customer_ref_id
left join yampi.order_addresses ya
  on ya.merchant_id = yo.merchant_id
  and ya.yampi_order_id = yo.yampi_order_id
  and ya.address_type = 'shipping'
where yo.payment_status in ('paid', 'aprovado', 'approved')
  and not exists (
    select 1 from shipping.unified_orders uo
    where uo.source_platform = 'yampi'
      and uo.source_order_id = yo.yampi_order_id::text
  );

create or replace view shipping.pending_cartpanda_orders as
select
  co.id as cartpanda_row_id,
  co.shop_id,
  co.cartpanda_order_id,
  co.order_number,
  co.integration_event_id,
  co.payment_status,
  co.total_cents,
  co.shipping_cents,
  co.source_created_at,
  cc.full_name as customer_name,
  cc.email as customer_email,
  cc.phone as customer_phone,
  cc.cpf as customer_cpf,
  ca.name as shipping_name,
  ca.address1 as shipping_address,
  ca.house_no as shipping_number,
  ca.compartment as shipping_complement,
  ca.neighborhood as shipping_neighborhood,
  ca.city as shipping_city,
  ca.province_code as shipping_state,
  ca.zip as shipping_zip,
  ca.country_code as shipping_country
from cartpanda.orders co
left join cartpanda.customers cc on cc.id = co.customer_ref_id
left join cartpanda.order_addresses ca
  on ca.shop_id = co.shop_id
  and ca.cartpanda_order_id = co.cartpanda_order_id
  and ca.address_type = 'shipping'
where co.payment_status in ('paid', 'aprovado', 'approved')
  and not exists (
    select 1 from shipping.unified_orders uo
    where uo.source_platform = 'cartpanda'
      and uo.source_order_id = co.cartpanda_order_id::text
  );

-- =============================================================================
-- RPC functions para o shipping-order-unifier (chamadas via service_role)
-- =============================================================================

create or replace function public.get_pending_yampi_shipping_orders()
returns setof shipping.pending_yampi_orders
language sql
security definer
stable
as $$
  select * from shipping.pending_yampi_orders limit 50;
$$;

create or replace function public.get_pending_cartpanda_shipping_orders()
returns setof shipping.pending_cartpanda_orders
language sql
security definer
stable
as $$
  select * from shipping.pending_cartpanda_orders limit 50;
$$;

grant execute on function public.get_pending_yampi_shipping_orders() to service_role;
grant execute on function public.get_pending_cartpanda_shipping_orders() to service_role;
