create schema if not exists cartpanda;

create table if not exists cartpanda.customers (
  id bigint generated by default as identity primary key,
  shop_id bigint not null,
  cartpanda_customer_id bigint not null,
  first_name text,
  last_name text,
  full_name text,
  email text,
  phone text,
  cpf text,
  cnpj text,
  source text,
  raw jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (shop_id, cartpanda_customer_id)
);

create index if not exists idx_cartpanda_customers_email
  on cartpanda.customers (lower(email));

create table if not exists cartpanda.orders (
  id bigint generated by default as identity primary key,
  integration_event_id bigint references integrations.integration_events(id) on delete set null,
  shop_id bigint not null,
  cartpanda_order_id bigint not null,
  order_name text,
  order_number text,
  customer_ref_id bigint references cartpanda.customers(id) on delete set null,
  event_name text not null,
  event_time timestamptz,
  order_status text,
  fulfillment_status text,
  payment_status text,
  payment_type text,
  payment_gateway text,
  currency text not null default 'BRL',
  subtotal_cents integer not null default 0,
  products_cents integer not null default 0,
  shipping_cents integer not null default 0,
  discount_cents integer not null default 0,
  tax_cents integer not null default 0,
  total_cents integer not null default 0,
  installments integer,
  installments_rate text,
  email text,
  phone text,
  browser_ip text,
  source_name text,
  tracking_number text,
  tracking_numbers text,
  pix_code text,
  pix_limit_at timestamptz,
  boleto_link text,
  boleto_limit_at timestamptz,
  thank_you_page text,
  checkout_link text,
  processed_at timestamptz,
  cancelled_at timestamptz,
  closed_at timestamptz,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  raw jsonb not null,
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shop_id, cartpanda_order_id)
);

create index if not exists idx_cartpanda_orders_event_time
  on cartpanda.orders (event_time desc);
create index if not exists idx_cartpanda_orders_payment_status
  on cartpanda.orders (payment_status);
create index if not exists idx_cartpanda_orders_order_status
  on cartpanda.orders (order_status);

drop trigger if exists trg_cartpanda_orders_updated_at on cartpanda.orders;
create trigger trg_cartpanda_orders_updated_at
before update on cartpanda.orders
for each row execute function integrations.set_updated_at();

create table if not exists cartpanda.order_addresses (
  id bigint generated by default as identity primary key,
  shop_id bigint not null,
  cartpanda_order_id bigint not null,
  address_type text not null default 'shipping'
    check (address_type in ('shipping', 'billing')),
  name text,
  first_name text,
  last_name text,
  company text,
  phone text,
  address1 text,
  address2 text,
  address text,
  house_no text,
  compartment text,
  neighborhood text,
  city text,
  province text,
  province_code text,
  country text,
  country_code text,
  zip text,
  raw jsonb,
  ingested_at timestamptz not null default now(),
  unique (shop_id, cartpanda_order_id, address_type)
);

create index if not exists idx_cartpanda_order_addresses_order
  on cartpanda.order_addresses (shop_id, cartpanda_order_id);

create table if not exists cartpanda.order_items (
  id bigint generated by default as identity primary key,
  shop_id bigint not null,
  cartpanda_order_id bigint not null,
  cartpanda_item_id bigint not null,
  product_id bigint,
  variant_id bigint,
  sku text,
  title text,
  variant_title text,
  name text,
  quantity integer not null default 1 check (quantity > 0),
  unit_price_cents integer not null default 0,
  requires_shipping boolean,
  is_digital boolean,
  status_id text,
  shipping_method text,
  raw jsonb not null,
  ingested_at timestamptz not null default now(),
  unique (shop_id, cartpanda_order_id, cartpanda_item_id)
);

create index if not exists idx_cartpanda_order_items_order
  on cartpanda.order_items (shop_id, cartpanda_order_id);
create index if not exists idx_cartpanda_order_items_product
  on cartpanda.order_items (product_id);

create table if not exists cartpanda.order_transactions (
  id bigint generated by default as identity primary key,
  shop_id bigint not null,
  cartpanda_order_id bigint not null,
  transaction_ref text not null,
  gateway text,
  payment_type text,
  authorization_code text,
  payment_id text,
  status text,
  amount_cents integer,
  installments integer,
  installments_rate text,
  pix_code text,
  pix_limit_at timestamptz,
  boleto_link text,
  boleto_limit_at timestamptz,
  currency text,
  raw jsonb,
  ingested_at timestamptz not null default now(),
  unique (shop_id, cartpanda_order_id, transaction_ref)
);

create index if not exists idx_cartpanda_order_transactions_order
  on cartpanda.order_transactions (shop_id, cartpanda_order_id);
create index if not exists idx_cartpanda_order_transactions_status
  on cartpanda.order_transactions (status);

create table if not exists cartpanda.order_metadata (
  id bigint generated by default as identity primary key,
  shop_id bigint not null,
  cartpanda_order_id bigint not null,
  meta_key text not null,
  meta_value text,
  raw jsonb,
  ingested_at timestamptz not null default now(),
  unique (shop_id, cartpanda_order_id, meta_key)
);

create index if not exists idx_cartpanda_order_metadata_order
  on cartpanda.order_metadata (shop_id, cartpanda_order_id);

grant usage on schema cartpanda to service_role;
grant select, insert, update, delete on table cartpanda.customers to service_role;
grant select, insert, update, delete on table cartpanda.orders to service_role;
grant select, insert, update, delete on table cartpanda.order_addresses to service_role;
grant select, insert, update, delete on table cartpanda.order_items to service_role;
grant select, insert, update, delete on table cartpanda.order_transactions to service_role;
grant select, insert, update, delete on table cartpanda.order_metadata to service_role;
grant usage, select on all sequences in schema cartpanda to service_role;
