create schema if not exists integrations;

create table if not exists integrations.stores (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_integrations_stores_updated_at on integrations.stores;
create trigger trg_integrations_stores_updated_at
before update on integrations.stores
for each row execute function integrations.set_updated_at();

create table if not exists integrations.store_external_links (
  id bigint generated by default as identity primary key,
  store_id uuid not null references integrations.stores(id) on delete cascade,
  source text not null check (source in ('yampi', 'cartpanda')),
  external_store_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source, external_store_id)
);

drop trigger if exists trg_integrations_store_external_links_updated_at on integrations.store_external_links;
create trigger trg_integrations_store_external_links_updated_at
before update on integrations.store_external_links
for each row execute function integrations.set_updated_at();

create index if not exists idx_store_external_links_store_id
  on integrations.store_external_links (store_id);

create table if not exists integrations.store_members (
  id bigint generated by default as identity primary key,
  store_id uuid not null references integrations.stores(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member'
    check (role in ('owner', 'admin', 'member', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, user_id)
);

drop trigger if exists trg_integrations_store_members_updated_at on integrations.store_members;
create trigger trg_integrations_store_members_updated_at
before update on integrations.store_members
for each row execute function integrations.set_updated_at();

create index if not exists idx_store_members_user_id
  on integrations.store_members (user_id);

create index if not exists idx_store_members_store_id
  on integrations.store_members (store_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'integration_events_store_id_fkey'
      and conrelid = 'integrations.integration_events'::regclass
  ) then
    alter table integrations.integration_events
      add constraint integration_events_store_id_fkey
      foreign key (store_id)
      references integrations.stores(id)
      on delete set null;
  end if;
end
$$;

create index if not exists idx_integration_events_store_id
  on integrations.integration_events (store_id);

create index if not exists idx_yampi_orders_integration_event_id
  on yampi.orders (integration_event_id);

create index if not exists idx_cartpanda_orders_integration_event_id
  on cartpanda.orders (integration_event_id);

create or replace function integrations.has_store_access(p_store_id uuid)
returns boolean
language sql
stable
security definer
set search_path = integrations, public
as $$
  select exists (
    select 1
    from integrations.store_members sm
    where sm.store_id = p_store_id
      and sm.user_id = (select auth.uid())
  );
$$;

revoke all on function integrations.has_store_access(uuid) from public;
grant execute on function integrations.has_store_access(uuid) to authenticated;
grant execute on function integrations.has_store_access(uuid) to service_role;

grant usage on schema integrations to authenticated;
grant usage on schema yampi to authenticated;
grant usage on schema cartpanda to authenticated;

grant select on table integrations.stores to authenticated;
grant select on table integrations.store_members to authenticated;
grant select on table yampi.customers to authenticated;
grant select on table yampi.orders to authenticated;
grant select on table yampi.order_addresses to authenticated;
grant select on table yampi.order_items to authenticated;
grant select on table yampi.order_transactions to authenticated;
grant select on table yampi.order_metadata to authenticated;
grant select on table cartpanda.customers to authenticated;
grant select on table cartpanda.orders to authenticated;
grant select on table cartpanda.order_addresses to authenticated;
grant select on table cartpanda.order_items to authenticated;
grant select on table cartpanda.order_transactions to authenticated;
grant select on table cartpanda.order_metadata to authenticated;

grant usage on schema integrations to service_role;
grant select, insert, update, delete on table integrations.stores to service_role;
grant select, insert, update, delete on table integrations.store_external_links to service_role;
grant select, insert, update, delete on table integrations.store_members to service_role;
grant usage, select on all sequences in schema integrations to service_role;

alter table integrations.stores enable row level security;
alter table integrations.store_members enable row level security;
alter table yampi.customers enable row level security;
alter table yampi.orders enable row level security;
alter table yampi.order_addresses enable row level security;
alter table yampi.order_items enable row level security;
alter table yampi.order_transactions enable row level security;
alter table yampi.order_metadata enable row level security;
alter table cartpanda.customers enable row level security;
alter table cartpanda.orders enable row level security;
alter table cartpanda.order_addresses enable row level security;
alter table cartpanda.order_items enable row level security;
alter table cartpanda.order_transactions enable row level security;
alter table cartpanda.order_metadata enable row level security;

drop policy if exists stores_authenticated_select on integrations.stores;
create policy stores_authenticated_select
on integrations.stores
for select
to authenticated
using (integrations.has_store_access(id));

drop policy if exists stores_service_role_all on integrations.stores;
create policy stores_service_role_all
on integrations.stores
for all
to service_role
using (true)
with check (true);

drop policy if exists store_members_authenticated_select_own on integrations.store_members;
create policy store_members_authenticated_select_own
on integrations.store_members
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists store_members_service_role_all on integrations.store_members;
create policy store_members_service_role_all
on integrations.store_members
for all
to service_role
using (true)
with check (true);

drop policy if exists yampi_orders_authenticated_select on yampi.orders;
create policy yampi_orders_authenticated_select
on yampi.orders
for select
to authenticated
using (
  exists (
    select 1
    from integrations.integration_events ie
    where ie.id = integration_event_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists yampi_orders_service_role_all on yampi.orders;
create policy yampi_orders_service_role_all
on yampi.orders
for all
to service_role
using (true)
with check (true);

drop policy if exists yampi_customers_authenticated_select on yampi.customers;
create policy yampi_customers_authenticated_select
on yampi.customers
for select
to authenticated
using (
  exists (
    select 1
    from yampi.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.yampi_customer_ref_id = customers.id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists yampi_customers_service_role_all on yampi.customers;
create policy yampi_customers_service_role_all
on yampi.customers
for all
to service_role
using (true)
with check (true);

drop policy if exists yampi_order_addresses_authenticated_select on yampi.order_addresses;
create policy yampi_order_addresses_authenticated_select
on yampi.order_addresses
for select
to authenticated
using (
  exists (
    select 1
    from yampi.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.merchant_id = order_addresses.merchant_id
      and o.yampi_order_id = order_addresses.yampi_order_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists yampi_order_addresses_service_role_all on yampi.order_addresses;
create policy yampi_order_addresses_service_role_all
on yampi.order_addresses
for all
to service_role
using (true)
with check (true);

drop policy if exists yampi_order_items_authenticated_select on yampi.order_items;
create policy yampi_order_items_authenticated_select
on yampi.order_items
for select
to authenticated
using (
  exists (
    select 1
    from yampi.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.merchant_id = order_items.merchant_id
      and o.yampi_order_id = order_items.yampi_order_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists yampi_order_items_service_role_all on yampi.order_items;
create policy yampi_order_items_service_role_all
on yampi.order_items
for all
to service_role
using (true)
with check (true);

drop policy if exists yampi_order_transactions_authenticated_select on yampi.order_transactions;
create policy yampi_order_transactions_authenticated_select
on yampi.order_transactions
for select
to authenticated
using (
  exists (
    select 1
    from yampi.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.merchant_id = order_transactions.merchant_id
      and o.yampi_order_id = order_transactions.yampi_order_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists yampi_order_transactions_service_role_all on yampi.order_transactions;
create policy yampi_order_transactions_service_role_all
on yampi.order_transactions
for all
to service_role
using (true)
with check (true);

drop policy if exists yampi_order_metadata_authenticated_select on yampi.order_metadata;
create policy yampi_order_metadata_authenticated_select
on yampi.order_metadata
for select
to authenticated
using (
  exists (
    select 1
    from yampi.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.merchant_id = order_metadata.merchant_id
      and o.yampi_order_id = order_metadata.yampi_order_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists yampi_order_metadata_service_role_all on yampi.order_metadata;
create policy yampi_order_metadata_service_role_all
on yampi.order_metadata
for all
to service_role
using (true)
with check (true);

drop policy if exists cartpanda_orders_authenticated_select on cartpanda.orders;
create policy cartpanda_orders_authenticated_select
on cartpanda.orders
for select
to authenticated
using (
  exists (
    select 1
    from integrations.integration_events ie
    where ie.id = integration_event_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists cartpanda_orders_service_role_all on cartpanda.orders;
create policy cartpanda_orders_service_role_all
on cartpanda.orders
for all
to service_role
using (true)
with check (true);

drop policy if exists cartpanda_customers_authenticated_select on cartpanda.customers;
create policy cartpanda_customers_authenticated_select
on cartpanda.customers
for select
to authenticated
using (
  exists (
    select 1
    from cartpanda.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.customer_ref_id = customers.id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists cartpanda_customers_service_role_all on cartpanda.customers;
create policy cartpanda_customers_service_role_all
on cartpanda.customers
for all
to service_role
using (true)
with check (true);

drop policy if exists cartpanda_order_addresses_authenticated_select on cartpanda.order_addresses;
create policy cartpanda_order_addresses_authenticated_select
on cartpanda.order_addresses
for select
to authenticated
using (
  exists (
    select 1
    from cartpanda.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.shop_id = order_addresses.shop_id
      and o.cartpanda_order_id = order_addresses.cartpanda_order_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists cartpanda_order_addresses_service_role_all on cartpanda.order_addresses;
create policy cartpanda_order_addresses_service_role_all
on cartpanda.order_addresses
for all
to service_role
using (true)
with check (true);

drop policy if exists cartpanda_order_items_authenticated_select on cartpanda.order_items;
create policy cartpanda_order_items_authenticated_select
on cartpanda.order_items
for select
to authenticated
using (
  exists (
    select 1
    from cartpanda.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.shop_id = order_items.shop_id
      and o.cartpanda_order_id = order_items.cartpanda_order_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists cartpanda_order_items_service_role_all on cartpanda.order_items;
create policy cartpanda_order_items_service_role_all
on cartpanda.order_items
for all
to service_role
using (true)
with check (true);

drop policy if exists cartpanda_order_transactions_authenticated_select on cartpanda.order_transactions;
create policy cartpanda_order_transactions_authenticated_select
on cartpanda.order_transactions
for select
to authenticated
using (
  exists (
    select 1
    from cartpanda.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.shop_id = order_transactions.shop_id
      and o.cartpanda_order_id = order_transactions.cartpanda_order_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists cartpanda_order_transactions_service_role_all on cartpanda.order_transactions;
create policy cartpanda_order_transactions_service_role_all
on cartpanda.order_transactions
for all
to service_role
using (true)
with check (true);

drop policy if exists cartpanda_order_metadata_authenticated_select on cartpanda.order_metadata;
create policy cartpanda_order_metadata_authenticated_select
on cartpanda.order_metadata
for select
to authenticated
using (
  exists (
    select 1
    from cartpanda.orders o
    join integrations.integration_events ie on ie.id = o.integration_event_id
    where o.shop_id = order_metadata.shop_id
      and o.cartpanda_order_id = order_metadata.cartpanda_order_id
      and ie.store_id is not null
      and integrations.has_store_access(ie.store_id)
  )
);

drop policy if exists cartpanda_order_metadata_service_role_all on cartpanda.order_metadata;
create policy cartpanda_order_metadata_service_role_all
on cartpanda.order_metadata
for all
to service_role
using (true)
with check (true);
