-- ============================================================================
-- Packaging Rules Engine - Schema
-- Permite configurar regras de embalagem por SKU, categoria, combinação,
-- contenção e fallback, com prioridade configurável.
-- ============================================================================

-- 1. Categorias de produto (sementes, bandeja, kit, etc.)
CREATE TABLE shipping.product_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_product_categories_updated_at
  BEFORE UPDATE ON shipping.product_categories
  FOR EACH ROW EXECUTE FUNCTION integrations.set_updated_at();

-- 2. Regras de embalagem
CREATE TABLE shipping.packaging_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  rule_type text NOT NULL CHECK (rule_type IN ('sku_fixed', 'category_base', 'combination', 'fallback')),
  priority int NOT NULL DEFAULT 100, -- menor = maior prioridade
  -- Critérios de match (depende do rule_type)
  match_sku text,                     -- para sku_fixed
  match_category_id bigint            -- para category_base
    REFERENCES shipping.product_categories(id) ON DELETE SET NULL,
  match_category_ids jsonb DEFAULT '[]', -- para combination: array de category IDs
  -- Dimensões resultantes
  height_cm numeric(8,2) NOT NULL,
  width_cm numeric(8,2) NOT NULL,
  length_cm numeric(8,2) NOT NULL,
  weight_grams_override int,          -- sobrescreve peso se definido
  -- Controle
  active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_packaging_rules_updated_at
  BEFORE UPDATE ON shipping.packaging_rules
  FOR EACH ROW EXECUTE FUNCTION integrations.set_updated_at();

-- 3. Contenção: qual categoria cabe dentro de qual
CREATE TABLE shipping.packaging_containment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  container_category_id bigint NOT NULL
    REFERENCES shipping.product_categories(id) ON DELETE CASCADE,
  contained_category_id bigint NOT NULL
    REFERENCES shipping.product_categories(id) ON DELETE CASCADE,
  max_qty int,            -- null = ilimitado
  notes text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(container_category_id, contained_category_id)
);

CREATE TRIGGER trg_packaging_containment_updated_at
  BEFORE UPDATE ON shipping.packaging_containment
  FOR EACH ROW EXECUTE FUNCTION integrations.set_updated_at();

-- 4. Mapeamento SKU → Categoria
CREATE TABLE shipping.product_category_map (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text NOT NULL,
  product_name text,
  category_id bigint NOT NULL
    REFERENCES shipping.product_categories(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(sku, category_id)
);

-- ============================================================================
-- Grants
-- ============================================================================
GRANT ALL ON shipping.product_categories TO service_role;
GRANT ALL ON shipping.packaging_rules TO service_role;
GRANT ALL ON shipping.packaging_containment TO service_role;
GRANT ALL ON shipping.product_category_map TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON shipping.product_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON shipping.packaging_rules TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON shipping.packaging_containment TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON shipping.product_category_map TO authenticated;

GRANT SELECT ON shipping.product_categories TO anon;
GRANT SELECT ON shipping.packaging_rules TO anon;
GRANT SELECT ON shipping.packaging_containment TO anon;
GRANT SELECT ON shipping.product_category_map TO anon;

-- ============================================================================
-- Seed: Categorias iniciais
-- ============================================================================
INSERT INTO shipping.product_categories (slug, name, description) VALUES
  ('sementes', 'Sementes', 'Pacotes de sementes'),
  ('bandeja', 'Bandeja', 'Bandejas para cultivo'),
  ('kit', 'Kit', 'Kits prontos com embalagem definida');

-- ============================================================================
-- Seed: Regras iniciais
-- ============================================================================

-- SKU Fixo (prioridade 10) — kits com embalagem definida
INSERT INTO shipping.packaging_rules
  (name, description, rule_type, priority, match_sku, height_cm, width_cm, length_cm, notes)
VALUES
  ('Kit 000158', 'Kit fechado com embalagem fixa', 'sku_fixed', 10, '000158', 12, 15, 20,
   'Dimensoes fixas: 12x15x20'),
  ('Kit KIT2', 'Kit fechado com embalagem fixa', 'sku_fixed', 10, 'KIT2', 4, 12, 20,
   'Dimensoes fixas: 4x12x20');

-- Categoria Base (prioridade 40-50)
INSERT INTO shipping.packaging_rules
  (name, description, rule_type, priority, match_category_id, height_cm, width_cm, length_cm, notes)
VALUES
  ('Pacote com Bandeja', 'Dimensoes quando pedido contem bandeja', 'category_base', 40,
   (SELECT id FROM shipping.product_categories WHERE slug = 'bandeja'),
   4, 15, 20, 'Bandeja determina o pacote base'),
  ('Pacote de Sementes', 'Dimensoes para pedidos com apenas sementes', 'category_base', 50,
   (SELECT id FROM shipping.product_categories WHERE slug = 'sementes'),
   2, 10, 15, 'Pacote pequeno para sementes');

-- Fallback (prioridade 999)
INSERT INTO shipping.packaging_rules
  (name, description, rule_type, priority, height_cm, width_cm, length_cm, notes)
VALUES
  ('Pacote Padrao (Fallback)', 'Dimensoes padrao quando nenhuma regra se aplica',
   'fallback', 999, 2, 11, 16, 'Fallback universal');

-- ============================================================================
-- Seed: Contenção — sementes cabem dentro da bandeja
-- ============================================================================
INSERT INTO shipping.packaging_containment
  (container_category_id, contained_category_id, notes)
VALUES
  ((SELECT id FROM shipping.product_categories WHERE slug = 'bandeja'),
   (SELECT id FROM shipping.product_categories WHERE slug = 'sementes'),
   'Sementes cabem dentro da bandeja sem aumentar o pacote');
