create extension if not exists pgcrypto;

-- Keep core schema present because local PostgREST config exposes it in PGRST_DB_SCHEMAS.
create schema if not exists core;
create schema if not exists integrations;
create schema if not exists yampi;

create or replace function integrations.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists integrations.integration_events (
  id bigint generated by default as identity primary key,
  received_at timestamptz not null default now(),
  source text not null check (source in ('yampi', 'cartpanda')),
  event_type text not null,
  external_entity_type text,
  external_entity_id text,
  store_id uuid,
  dedupe_key text not null unique,
  status text not null default 'received'
    check (status in ('received', 'processing', 'processed', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  processed_at timestamptz,
  error text,
  signature text,
  headers jsonb,
  payload jsonb not null
);

create index if not exists idx_events_status
  on integrations.integration_events (status, received_at desc);
create index if not exists idx_events_source_time
  on integrations.integration_events (source, received_at desc);
create index if not exists idx_events_entity
  on integrations.integration_events (external_entity_type, external_entity_id);
create index if not exists idx_events_payload_gin
  on integrations.integration_events using gin (payload jsonb_path_ops);

create table if not exists integrations.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  job_type text not null,
  priority integer not null default 100,
  event_id bigint references integrations.integration_events(id) on delete set null,
  dedupe_key text not null unique,
  status text not null default 'queued'
    check (status in ('queued', 'processing', 'done', 'failed', 'dead')),
  attempts integer not null default 0,
  max_attempts integer not null default 10,
  run_after timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  last_error text
);

create index if not exists idx_jobs_pick
  on integrations.jobs (status, run_after, priority, id);
create index if not exists idx_jobs_event
  on integrations.jobs (event_id);

drop trigger if exists trg_jobs_updated_at on integrations.jobs;
create trigger trg_jobs_updated_at
before update on integrations.jobs
for each row execute function integrations.set_updated_at();

create table if not exists yampi.customers (
  id bigint generated by default as identity primary key,
  merchant_id bigint not null,
  yampi_customer_id bigint not null,
  name text,
  first_name text,
  last_name text,
  email text,
  cpf text,
  phone_full_number text,
  phone_area_code text,
  phone_number text,
  utm_source text,
  utm_campaign text,
  ip text,
  raw jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (merchant_id, yampi_customer_id)
);

create index if not exists idx_yampi_customers_email
  on yampi.customers (lower(email));

create table if not exists yampi.orders (
  id bigint generated by default as identity primary key,
  integration_event_id bigint references integrations.integration_events(id) on delete set null,
  merchant_id bigint not null,
  yampi_order_id bigint not null,
  order_number bigint,
  yampi_customer_ref_id bigint references yampi.customers(id) on delete set null,
  event_name text not null,
  event_time timestamptz,
  status_alias text,
  status_name text,
  payment_alias text,
  payment_status text,
  shipment_service text,
  shipment_service_id text,
  track_code text,
  track_url text,
  currency text not null default 'BRL',
  total_cents integer not null default 0,
  products_cents integer not null default 0,
  shipping_cents integer not null default 0,
  discount_cents integer not null default 0,
  utm_source text,
  utm_campaign text,
  utm_medium text,
  utm_content text,
  utm_term text,
  ip text,
  device text,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  raw jsonb not null,
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (merchant_id, yampi_order_id)
);

create index if not exists idx_yampi_orders_event_time
  on yampi.orders (event_time desc);
create index if not exists idx_yampi_orders_payment_status
  on yampi.orders (payment_status);
create index if not exists idx_yampi_orders_status_alias
  on yampi.orders (status_alias);

drop trigger if exists trg_yampi_orders_updated_at on yampi.orders;
create trigger trg_yampi_orders_updated_at
before update on yampi.orders
for each row execute function integrations.set_updated_at();

create table if not exists yampi.order_addresses (
  id bigint generated by default as identity primary key,
  merchant_id bigint not null,
  yampi_order_id bigint not null,
  address_type text not null default 'shipping'
    check (address_type in ('shipping', 'pickup')),
  receiver text,
  zipcode text,
  street text,
  street_number text,
  complement text,
  reference text,
  neighborhood text,
  city text,
  state text,
  country text,
  full_address text,
  raw jsonb,
  ingested_at timestamptz not null default now(),
  unique (merchant_id, yampi_order_id, address_type)
);

create index if not exists idx_yampi_order_addresses_order
  on yampi.order_addresses (merchant_id, yampi_order_id);

create table if not exists yampi.order_items (
  id bigint generated by default as identity primary key,
  merchant_id bigint not null,
  yampi_order_id bigint not null,
  yampi_item_id bigint not null,
  product_id bigint,
  sku_id bigint,
  item_sku text,
  title text,
  bundle_id bigint,
  bundle_name text,
  quantity integer not null default 1 check (quantity > 0),
  unit_price_cents integer not null default 0,
  shipment_cost_cents integer not null default 0,
  is_digital boolean,
  gift boolean,
  raw jsonb not null,
  ingested_at timestamptz not null default now(),
  unique (merchant_id, yampi_order_id, yampi_item_id)
);

create index if not exists idx_yampi_order_items_order
  on yampi.order_items (merchant_id, yampi_order_id);
create index if not exists idx_yampi_order_items_product
  on yampi.order_items (product_id);

create table if not exists yampi.order_transactions (
  id bigint generated by default as identity primary key,
  merchant_id bigint not null,
  yampi_order_id bigint not null,
  yampi_transaction_id bigint not null,
  payment_alias text,
  payment_name text,
  gateway_transaction_id text,
  gateway_order_id text,
  status text,
  amount_cents integer,
  installments integer,
  installment_value_cents integer,
  pix_qr_code text,
  pix_expiration_at timestamptz,
  authorized_at timestamptz,
  captured_at timestamptz,
  cancelled_at timestamptz,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  raw jsonb,
  ingested_at timestamptz not null default now(),
  unique (merchant_id, yampi_order_id, yampi_transaction_id)
);

create index if not exists idx_yampi_order_transactions_order
  on yampi.order_transactions (merchant_id, yampi_order_id);
create index if not exists idx_yampi_order_transactions_status
  on yampi.order_transactions (status);

create table if not exists yampi.order_metadata (
  id bigint generated by default as identity primary key,
  merchant_id bigint not null,
  yampi_order_id bigint not null,
  meta_key text not null,
  meta_value text,
  raw jsonb,
  ingested_at timestamptz not null default now(),
  unique (merchant_id, yampi_order_id, meta_key)
);

create index if not exists idx_yampi_order_metadata_order
  on yampi.order_metadata (merchant_id, yampi_order_id);

grant usage on schema integrations to service_role;
grant usage on schema yampi to service_role;

grant select, insert, update, delete on table integrations.integration_events to service_role;
grant select, insert, update, delete on table integrations.jobs to service_role;
grant usage, select on all sequences in schema integrations to service_role;

grant select, insert, update, delete on table yampi.customers to service_role;
grant select, insert, update, delete on table yampi.orders to service_role;
grant select, insert, update, delete on table yampi.order_addresses to service_role;
grant select, insert, update, delete on table yampi.order_items to service_role;
grant select, insert, update, delete on table yampi.order_transactions to service_role;
grant select, insert, update, delete on table yampi.order_metadata to service_role;
grant usage, select on all sequences in schema yampi to service_role;
